


export const catchError(fun)=>{
    return (re)=>{}
}